ctmrbio/stag-mwc

.gitignore, Snakefile, config.yaml, rules/mappers/bowtie2.smk
Add bowtie2 mapping step. Introduces new hierarchy in `config.yaml` to select which mappers to run. Also introduces new `rules/mappers` folder that will contain rules for different mappers. Also adds read counts, coverage statistics, etc via `pileup.sh` from BBTools.
=> Add Bowtie2

Snakefile, config.yaml, envs/centrifuge.yaml, rules/taxonomic_profiling/centrifuge.smk
This PR adds Centrifuge as an alternative taxonomic profiling tool. It includes a rule, `download_centrifuge_database`, that can be manually triggered to download the complete bacteria, archaea, human, virus database database (just run `snakemake download_centrifuge_database` to run only that rule).
=> Add taxonomic profiler: Centrifuge. Closes #5

Snakefile, config.yaml, envs/metaphlan2.yaml, rules/taxonomic_profiling/metaphlan2.smk
This PR adds a set of MetaPhlAn2 rules. 
One of the rules enables automatic download of the required MetaPhlAn2 marker gene database by calling `snakemake build_metaphlan2_index`. There is a rule that combines all MetaPhlAn2 outputs into a single table at the end. I'm thinking to extend this to produce Krona plots for all mpa2 outputs as well. 
One more thing: as StaG-mwc is becoming larger and larger I decided to set all steps to `False` except for the preprocessing steps. It makes it easier to get started without being hit with a ton of warning messages about missing databases etc when you have just downloaded the workflow and try running it for the first time.
=> Metaphlan2

Snakefile, config.yaml, rules/mappers/bbmap.smk
This PR adds BBMap as an optional step to the workflow, to map against any database that the user provides.
It also cleans up the config file a bit. Closes #6
=> Add BBMap for generic read mapping

.gitignore, Snakefile, config.yaml, envs/python.yaml, rules/sketch_compare/sketch_compare.smk, scripts/plot_sketch_comparison_heatmap.py
This PR adds MinHash-based all-vs-all sample comparisons using BBMap's `sketch.sh`/`comparesketch.sh` tools. It plots a simple summary heatmap plot of the all-vs-all similarity matrix using [Seaborn](http://seaborn.pydata.org/). It's a rough tool, but it's quick to run, requires little resources, and hopefully gives a quick and easy-to-look-at plot to assess overall sample similarity.
I set it to be off by default in `config.yaml`. 
Closes #16
=> Add MinHash sketch-based all-vs-all sample comparison PDF plot

.gitignore, config.yaml, envs/stag-mwc.yaml, rules/mappers/bbmap.smk, rules/mappers/bowtie2.smk, utils/convert_IGC_annotation.py
This PR adds a step on top of the BBMap/Bowtie2 mapping steps to summarize read counts per annotated feature. It uses [featureCounts](http://bioinf.wehi.edu.au/featureCounts/) for the read count summaries, which uses annotations in GTF format. 
The featureCounts step is optional, and is triggered on whether the featureCounts annotation setting in `config.yaml` holds a value other than the empty string. 
The way it is implemented, it is in fact possible to use also annotations in SAF (simple annotation format) thanks to support by `featureCounts`. To use SAF annotations instead of GTF, simply input the SAF annotation file as a parameter to the featureCounts annotation setting in `config.yaml`, and put the string `-F SAF` as an option in the featureCounts extra setting in `config.yaml`.
=> Feature counts

rules/mappers/bbmap.smk, rules/mappers/bowtie2.smk, scripts/make_count_table.py
Add basic summary counts table for mappers (BBMap/Bowtie2). 
A simple Python script that summarizes observed counts per annotation.
The script will produce a clean table for annotations of a database with reference sequences `ref1`, `ref2`, `ref3`, and an annotation file like this:
```
ref1    annotation1
ref2    annotation2
ref3    annotation1
``` 
with spaces as tabs.
The output table will look something like this:
```
Annotation    sample1    sample2
annotation1              2                2
annotation2              1                3
```
... You get the idea.
=> Produce counts table for mappers

scripts/make_count_table.py
I tried to reduce the memory consumption of `make_count_table.py` by using numpy.  It made the code faster (about half the speed), but it does make memory usage more predictable. I finally decided to revert to the pre-numpy version 1.2.1, just because it's the fastest for the test data (that has mostly zero counts). The 1.2.1 implementation will have slightly higher memory consumption for data where most annotations have counts > 0, but if we notice it's not going to work for real-world data, we can change to the 2.1.0 version in f79f55d that has a more predictable memory consumption.
=> Use numpy in make_count_table.py

CONTRIBUTING.md, Snakefile, config.yaml, docs/source/conf.py, rules/antibiotic_resistance/megares.smk, rules/mappers/bbmap.smk, rules/mappers/bowtie2.smk, rules/preproc/bbcountunique.smk, rules/preproc/read_quality.smk, rules/preproc/remove_human.smk, rules/sketch_compare/sketch_compare.smk, rules/taxonomic_profiling/centrifuge.smk, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/metaphlan2.smk
Convert all input, outputs, and log statements to use pathlib instead of working with paths as strings.
A few minor annoyances, however; Snakemake support for pathlib is currently not complete, most promimently, expand statements and log file declarations cannot use pathlib objects at the moment, so they are explicitly converted to strings in the rule files. I plan to change this when Snakemake becomes fully compatible further on. 
I also introduce the develop branch in this PR, intending that the master branch of the repo should be considered stable and will only receive commits when enough new features have been added to the develop branch.
=> Use pathlib

.gitignore, CHANGELOG.md, README.md, Snakefile, cluster_configs/rackham/rackham.yaml, config.yaml, docs/source/modules.rst, envs/biobakery.yaml, envs/stag-mwc.yaml, rules/functional_profiling/humann2.smk, rules/taxonomic_profiling/metaphlan2.smk
Add rules to run [HUMAnN2](https://bitbucket.org/biobakery/humann2/) for functional profiling.
This PR adds:
* HUMAnN2 rules module
* HUMAnN2-specific settings to `config.yaml`
* documentation about the HUMAnN2 module
* updates to the changelog about adding HUMAnN2
=> Add HUMAnN2

CHANGELOG.md, Snakefile, config.yaml, docs/source/conf.py, docs/source/modules.rst, rules/antibiotic_resistance/groot.smk
Groot is picky about input read lengths matching the settings used during database index construction. This PR ensures all reads presented to groot are in a reasonable length span (defined in config file).
=> Read length window filtering before groot

CHANGELOG.md, cluster_configs/rackham/rackham.yaml, docs/source/modules.rst, rules/functional_profiling/humann2.smk
HUMAnN2 creates huge temporary files in the output folder (see #75). This PR does not solve the issue, but allows to limit the number of parallel humann2 rules to limit the impact. Run the workflow with `--resources humann2=X` to limit the number of rules executing in parallel to `X`. 
Because it seems it's impossible to change the temporary folder of HUMAnN2, it will keep working with all these files in the output folder, which is typically located on the slow shared file system, so I also increased the allocated time for humann2 jobs on Rackham to 12h instead of just 3h as it was previously.
=> Limit parallel humann2 processes

docs/source/modules.rst
Added links to the SAF and GTF definitions in the featureCounts documentation.
=> Add links to SAF and GTF definitions

config.yaml, docs/source/modules.rst, report/kaiju_table.rst, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/kraken2.smk, rules/taxonomic_profiling/metaphlan2.smk, scripts/join_tables.py
This PR generalizes `join_bracken_tables.py` into a more general table joining script that is useful also for joining the tables output from other tools. My long-term plan is to make sure the taxonomic profile tables from all methods in StaG have similar output.
=> Generalize join tables

CHANGELOG.md, docs/source/modules.rst, report/bracken_table_mpa.rst, report/kraken2_table_mpa.rst, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/kraken2.smk
Generalize output tables from taxonomic profilers to a more common output format, inspired by MetaPhlAn2 output format. One column with taxa description including full lineage, and one column per samples and their respective detected abundance/read counts.
=> Generalize taxprofile tables

Snakefile, docs/source/faq.rst, docs/source/index.rst, docs/source/running.rst, rules/antibiotic_resistance/groot.smk, rules/assembly/metawrap.smk, rules/functional_profiling/humann2.smk, rules/mappers/bbmap.smk, rules/mappers/bowtie2.smk, rules/preproc/host_removal.smk, rules/preproc/read_quality.smk, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/kraken2.smk, rules/taxonomic_profiling/metaphlan2.smk
I think a better way to implement DAG shortcut past QC could be to let the workflow do the symlinking, like in the implementation to allow skipping host_removal... 
I found some issues with the kraken2 bracken rules, so these commits are still important.
=> Enable shortcuts past QC and host_removal

CHANGELOG.md, envs/humann2.yaml, envs/metaphlan2.yaml, report/humann2_table.rst, rules/functional_profiling/humann2.smk, rules/taxonomic_profiling/metaphlan2.smk, scripts/plot_metaphlan2_heatmap.py
Lots of tweaks related to MPA2 and HUMAnN2. A work-around for formatting incompatibilities between the recent MPA2 version and the slightly older HUMAnN2 is there as well. 
It is important that MPA2 is run using the older v20_m200 database instead of the most recent one.
=> Update HUMAnN2 to 2.8, MPA2 to 2.96.1, and other tweaks

CHANGELOG.md, docs/source/modules.rst, rules/antibiotic_resistance/groot.smk, rules/functional_profiling/humann2.smk, rules/mappers/bbmap.smk, rules/mappers/bowtie2.smk, rules/preproc/host_removal.smk, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/kraken2.smk
Change all tsv outputs to txt so the tables don't get made into pretty HTML tables that screw up their formatting. If Snakemake even makes tsv to html conversion optional in the future we might change it back, because I prefer the .tsv extension over .txt.
=> Tsv to txt

config.yaml
Bracken continuously creates issues with the automation with scripts failing due to different reasons, incomplete files, etc.
=> Disable Bracken in CTMR automation branch

CHANGELOG.md, Snakefile
Ignore additional arguments to snakemake when creating report,
Intended to avoid shell escaping issue with complex arguments to e.g. Singularity, issue #160
=> Change report generation call

cluster_configs/ctmr_ucp/config.yaml, cluster_configs/ctmr_ucp/ctmr_ucp.yaml, cluster_configs/ctmr_ucp/slurm-jobscript.sh, cluster_configs/ctmr_ucp/slurm-status.py, cluster_configs/ctmr_ucp/slurm-submit.py
The CTMR UCP Slurm environment is a bit special, we have no accounts and all people currently use the same (default) partition `ctmr`. 
Currently, using the profile throws continuous error messages like 
```
sacct process error                                                                
Command '['sacct', '-P', '-b', '-j', '924', '-n']' returned non-zero exit status 1.
Slurm accounting storage is disabled                                               
```
because we haven't implemented Slurm accounts and accounting yet. It still runs, however.
=> Slurm profile for CTMR UCP environment

CHANGELOG.md, config.yaml, envs/Singularity.biobakery, envs/metaphlan.yaml, rules/taxonomic_profiling/kaiju.smk, rules/taxonomic_profiling/kraken2.smk, rules/taxonomic_profiling/metaphlan.smk
One quick fix to allow disabling Krona-related outputs. 
Second part of this PR should have been its own PR, but we change the container for mpa4-related rules to use the official biocontainer instead of our own biobakery-container.
=> Make krona optional, change to mpa4 biocontainer

CHANGELOG.md, Snakefile, config.yaml, docs/source/running.rst, rules/naive/bbcountunique.smk, rules/naive/sketch_compare.smk, rules/preproc/read_quality.smk, scripts/common.py
Add sample sheet as alternative option to specify input sample names and associated files. Uses a three-column format:
* `sample_id`: unique sample ID
* `fastq_1`: path to FASTQ with forward reads, can be local absolute/relative or S3 paths  e.g. `s3://bucketname/sample1_1.fq.gz`)
* `fastq_2`: path to FASTQ with reverse reads, can be local absolute/relative or S3 paths (e.g. `s3://bucketname/sample1_2.fq.gz`)
Added `samplesheet` config option to config file. If populated, expects TSV samplesheet at given path, which also ignores input dir settings (i.e. it is not possible to combine inputdir and samplesheet right now).
Snakemake makes it possible to dynamically set samplesheet like this:
```
snakemake --cores 4 --config samplesheet=path/to/samplesheet.tsv
```
=> Add samplesheet input option

config.yaml, docs/source/running.rst, samplesheet.tsv, scripts/common.py
This PR adds the possibility to read remote source data also via HTTP/HTTPS. I also added an example samplesheet that contains URLs to the small test data set that I use when testing StaG locally, I figure this kind of makes #196 unnecessary.
=> Enable remote sources over HTTP/HTTPS

CHANGELOG.md, workflow/rules/taxonomic_profiling/krakenuniq.smk
Add rule to merge paired reads input files to a single fasta so krakenuniq can run when host removal is skipped (which creates a symlink that is then fed as input to krakenuniq and it doesn't like that).
=> Merge reads to avoid feeding krakenuniq symlinks when skipping host removal

CHANGELOG.md, workflow/rules/taxonomic_profiling/krakenuniq.smk
@nilay-p discovered that KrakenUniq treated interleaved paired reads independently, and not as in the original implementation that we worked around with BBMap's `reformat.sh`. I replaced the interleaving step with a concatenation step instead, using BBMap's `fuse.sh`, which should replicate the behavior of KrakenUniq's `read_merger.pl` exactly.
=> KrakenUniq: Use fuse.sh instead of reformat.sh

CHANGELOG.md, config/config.yaml, docs/source/modules.rst, workflow/rules/mappers/bbmap.smk, workflow/rules/mappers/bowtie2.smk
In order to save disk space when mapping many samples against very large references databases it can be useful to let StaG delete all the BAM files produced from the mapping step. It of course leads to having to redo the mapping again if you want to rerun annotations or any other type of downstream analysis that requires the mapping results, but at least the option is there now.
Requested by #78
=> Make BAM files from mappers temporary

CHANGELOG.md, config/config.yaml, docs/source/modules.rst, workflow/Snakefile, workflow/envs/Singularity.biobakery, workflow/envs/humann.yaml, workflow/envs/metaphlan.yaml, workflow/rules/functional_profiling/humann.smk, workflow/rules/taxonomic_profiling/metaphlan.smk
Improve the HUMAnN rule by using `resources.tmpdir` instead of custom solution
=> Use resources.tmpdir instead of custom solution

CHANGELOG.md, config/config.yaml, docs/source/modules.rst, profiles/ctmr_gandalf/config.yaml, workflow/rules/preproc/host_removal.smk, workflow/rules/preproc/preprocessing_summary.smk, workflow/scripts/preprocessing_summary.py
Add bowtie2 as an option for host removal.
I have been thinking of ways to do host removal with both kraken2 and bowtie2 possible. The idea is that kraken2 runs quickly to remove the majority of reads, and then bowtie2 runs to scrub the remaining leftovers. I need to benchmark to see if it is worthwhile to implement, however. I guess it will only be meaningful if it substantially decreases the total time needed to run host removal compared to just running bowtie2 directly. 
To finish this PR I would like to have updated the read processing summary script so it can summarize read counts after any combination of fastp, kraken2, and bowtie2 preprocessing. As it is currently implemented it can only run if both fastp and kraken2 are utilized.
=> Improve host removal
